####################################################################################
#
# To create a  kubernete cronJob container, Please update the following things:
#
#    1.  In AWSIAMRole kind
#         a. Update metadata name
#         b. Update tge roleReference with your created role to access AWS
#     
#     2. In CronJob kind
#         a. Update the medadata name
#         b. Update the namespace
#         c. Update the schedule for cron
#         d. Update the Container name
#         e. Update the dcker repo path if required
#         f. Update the secret name with AWSIAMRole metadata name
#
####################################################################################

---
apiVersion: zalando.org/v1
kind: AWSIAMRole
metadata:
  name: < name of the secret >
spec:
  roleReference: <iam_role>

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: <name of the cronJob >
  namespace: < Update the namespace >
spec:
  schedule: < Schedule of the cron Job >
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: < Name of the container >
            image: yashwanthmoengage/alarms-checker:latest
            imagePullPolicy: Always
            command: ["/src/alarm_checker.py", "--input", "/input/aws/aws_inputs.yaml"]
            env:
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /meta/aws-iam/credentials.process
            volumeMounts:
            - name: aws-iam-credentials
              mountPath: /meta/aws-iam
              readOnly: true
          volumes:
          - name: aws-iam-credentials
            secret:
              secretName: < Name of the secret >
          restartPolicy: Never
